G-006/user-profile
madkorney/project-management-app pull request #9
Opened 2022-11-19 09:14 UTC by KarUladz

add user page
add modal user profile
refactor user buttons
 
![Screenshot from 2022-11-19 12-09-32](https://user-images.githubusercontent.com/96052707/202843812-091b6ad6-bfa3-4982-abfa-3a058a6dbf36.png)

![Screenshot from 2022-11-19 12-09-52](https://user-images.githubusercontent.com/96052707/202843806-b1d7041a-e712-4e5d-9a2d-e834cf0b4c7e.png)

![Screenshot from 2022-11-19 12-10-17](https://user-images.githubusercontent.com/96052707/202843817-603a3042-d1aa-4827-a1cd-8ca065aec480.png)

![Screenshot from 2022-11-19 12-10-35](https://user-images.githubusercontent.com/96052707/202843825-416513f8-101f-43f1-9dba-e4c4b6de8b28.png)

2022-11-19 12:18 UTC, madkorney approved these changes

2022-11-19 17:21 UTC, sylarBrest requested changes

2022-11-19 17:21 UTC, sylarBrest commented on src/components/Modal/ModalUser/modalUpdateUser.tsx
> +export default ModalUpdateUser;
модалка не должна обрабатывать логику, она должна только согласие получать. Плюс она становится второй, что не по ТЗ. По ТЗ модалка одна должна быть. Либо посмотри как я использую модалку, либо я сам потом отрефакторю

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/SignInPage/signInPage.tsx
> +
так, я удалял этот useEffect, как он всплыл тут? Этим занимается теперь PublicRoute

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/SignInPage/signInPage.tsx
> +      })
не понимаю зачем тут этот setTimeout

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/SignUpPage/signUpPage.tsx
> +      })
аналогично

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/UserPage/userPage.tsx
> +    </>
зачем оборачивать во фрагмент, если в итоге один div отрисовывается? И может его сделать как section?

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/UserPage/userPage.tsx
> +          <h2>Hi, {login && login.slice(0, 1).toUpperCase() + login.slice(1)}</h2>
здесь я бы всё-таки имя уже из базы доставал и выводил

2022-11-19 17:21 UTC, sylarBrest commented on src/redux/modalUserSlice.ts
> +export default userUpdateData.reducer;
что-то мне не нравится этот Слайс, что-то много в нём как мне кажется плюс-минус локальных переменных. Может подумать как его убрать

2022-11-19 17:21 UTC, sylarBrest commented on src/pages/UserPage/userPage.tsx
> +        />
по форме предложение - поля логин и имя заполнять данными

2022-11-20 12:17 UTC, sylarBrest approved these changes

2022-11-20 12:37 UTC, merged